version: "3"

services:
  mongodb:
    container_name: virtua_mongo
    image: mongo
    restart: always
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=aligoknl
      - DB_PASSWORD=Pl123456
      - DB_DATABASE=virtuagym
    ports:
      - "27017:27017"
    networks:
      - shared-network
    volumes:
      - data:/data/db

  server:
    container_name: virtua_server
    image: virtua_server
    restart: unless-stopped
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - shared-network
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  client:
    container_name: virtua_client
    image: virtua_client
    restart: unless-stopped
    build: ./client
    ports:
      - "9000:9000"
    volumes:
      - ./client/src:/app/src
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network:

volumes:
  data:
  logs:
