export const textInputsAttributes = [
  {
    id: 1,
    name: "title",
    type: "text",
    placeholder: "What is your club name?",
    errorMessage: "Club title should be between 3 and 30 characters long.",
    label: "Club Title",
    pattern: "^.{3,30}$",
    required: true,
    className: "create-club-input",
  },
  {
    id: 2,
    name: "street",
    type: "text",
    placeholder: "On which street is your club?",
    errorMessage: "Street should be entered.",
    label: "Street",
    required: true,
    className: "create-club-input",
  },
  {
    id: 3,
    name: "house_number",
    type: "text",
    placeholder: "In which building is your club?",
    label: "House Number",
    errorMessage: "House number should be entered.",
    required: true,
    className: "create-club-input",
  },
  {
    id: 4,
    name: "postcode",
    type: "text",
    placeholder: "What is the postcode of your club's place?",
    label: "Postcode",
    errorMessage: "Postcode should be entered.",
    required: true,
    className: "create-club-input",
  },
  {
    id: 5,
    list: "cities",
    name: "city",
    type: "text",
    placeholder: "In which city is your club?",
    label: "City",
    errorMessage: "City should be entered.",
    required: true,
    className: "create-club-input",
  },
  {
    id: 6,
    name: "website",
    type: "url",
    placeholder: "What is the website of your club? Ex: https://powergym.com",
    label: "Website",
    required: false,
    className: "create-club-input",
  },
  {
    id: 7,
    name: "credit",
    type: "number",
    placeholder:
      "How many credit will be deducted from your guests for every check in?",
    label: "Credit",
    required: true,
    errorMessage: "Credit should be entered and should be a number.",
    className: "create-club-input",
  },
];
